USE [andicator]
GO

/****** Object:  Table [dbo].[CHEQUEFIELDSPERM]    Script Date: 06/11/2017 22:35:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHEQUEFIELDSPERM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERID] [int] NOT NULL,
	[CHEQUENUMBER] [tinyint] NOT NULL,
	[MATURITYDATE] [tinyint] NOT NULL,
	[ENTRYDATE] [tinyint] NOT NULL,
	[PRICE] [tinyint] NOT NULL,
	[ACCOUNTNUMBER] [tinyint] NOT NULL,
	[ACCOUNTHOLDERNAME] [tinyint] NOT NULL,
	[PAYTYPE] [tinyint] NOT NULL,
	[INSURANCENUMBER] [tinyint] NOT NULL,
	[INSURANCECOMPANY] [tinyint] NOT NULL,
	[ARCHIVE] [tinyint] NOT NULL,
	[COMPANYID] [tinyint] NOT NULL,
	[REFFERFROM] [tinyint] NOT NULL,
	[REFFERDATE] [tinyint] NOT NULL,
	[BANKID] [tinyint] NOT NULL,
	[CHEQUEITEMS] [tinyint] NOT NULL,
 CONSTRAINT [PK_CHEQUEFIELDSPERM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

