USE [andicator]
GO

/****** Object:  Table [dbo].[ATTACHMENTCHEQUERECEIPT]    Script Date: 06/12/2017 00:05:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ATTACHMENTCHEQUERECEIPT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[RECEIPTID] [int] NOT NULL,
	[CONTENT] [image] NULL,
	[FILENAME] [varchar](250) NULL,
 CONSTRAINT [PK_ATTACHMENTCHEQUERECEIPT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ATTACHMENTCHEQUERECEIPT]  WITH NOCHECK ADD  CONSTRAINT [FK_ATTACHMENT_CHEQUERECEIPT] FOREIGN KEY([RECEIPTID])
REFERENCES [dbo].[CHEQUEREPLY] ([ID])
GO

ALTER TABLE [dbo].[ATTACHMENTCHEQUERECEIPT] CHECK CONSTRAINT [FK_ATTACHMENT_CHEQUERECEIPT]
GO

