USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER TABLE [dbo].[LETTERITEMSPERMISSION] ADD [ALARMSTARTDATE] tinyint NULL
GO
ALTER TABLE [dbo].[LETTERITEMSPERMISSION] ADD [BTN_AGENT] tinyint NULL
GO
USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER TABLE [dbo].[LETTERITEMSPERMISSION] ADD [BTN_DELETE] tinyint NULL
GO
