USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[REFERCHEQUE] (
[ID] int IDENTITY(1, 1) NOT NULL,
[CHEQUEID] int NOT NULL,
[REFERDATE] datetime NOT NULL,
[REFERFROMUSER] int NOT NULL,
[REFERTOUSER] int NULL,
CONSTRAINT [PK_dbo_CHEQUEREPLY_PK]
PRIMARY KEY CLUSTERED ([ID] )
WITH FILLFACTOR = 100
 ON [PRIMARY],
FOREIGN KEY ([CHEQUEID])
REFERENCES [dbo].[CHEQUE] ( [ID] )
)
ON [PRIMARY];
GO
