USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER VIEW [dbo].[VIEW_USERTREE]
AS
SELECT     dbo.USERTREE.ID, dbo.USERTREE.PARENTID, dbo.USERTREE.USERPATH, dbo.USERTREE.USERID, 
                      dbo.USERS.NAME + '  ' + dbo.USERS.FAMILY + '(' + dbo.USERS.USERNAME + ')' AS USERS_NAME, dbo.USERS.USERTYPE, dbo.USERS.ACTIVE
FROM         dbo.USERTREE LEFT OUTER JOIN
                      dbo.USERS ON dbo.USERTREE.USERID = dbo.USERS.ID
GO
