USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER TABLE [dbo].[LETTERITEMSPERMISSION] ADD [FASTACTION] tinyint NULL
GO
USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER VIEW [dbo].[VIEW_LETTERITEMSPERMISSION]
AS
SELECT     LETTERSUBJECT, INPUTREGISTERNUMBER, SUMMARY, INSURANCETYPEID, INSURANCENUMBER, INSURANCEDATE, LETTERSTATEID, 
                      COMPANYID, REFERENCEUSERID, RECIEVEDLETTERNUMBER, RECIEVEDLETTERDATE, ARCHIVE, FINALCONFIRM, USERID, BTNSEARCH, 
                      BTNLETTERSTATE, BTNUSERSREPLIES, ID, REFERTOMASTER, SHOWREFFRENCES,
                      ALARMSTARTDATE,BTN_AGENT,BTN_DELETE,FASTACTION
FROM         dbo.LETTERITEMSPERMISSION
GO
