/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.LETTERITEMSPERMISSION ADD
	DO_CHANING_TO_SEND tinyint NULL,
	DO_CHANING_TO_RECIEVE tinyint NULL
GO
COMMIT

USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER VIEW [dbo].[VIEW_LETTERITEMSPERMISSION]
AS
SELECT     LETTERSUBJECT, INPUTREGISTERNUMBER, SUMMARY, INSURANCETYPEID, INSURANCENUMBER, INSURANCEDATE, LETTERSTATEID, 
                      COMPANYID, REFERENCEUSERID, RECIEVEDLETTERNUMBER, RECIEVEDLETTERDATE, ARCHIVE, FINALCONFIRM, USERID, BTNSEARCH, 
                      BTNLETTERSTATE, BTNUSERSREPLIES, ID, REFERTOMASTER, SHOWREFFRENCES, ALARMSTARTDATE, BTN_AGENT, BTN_DELETE, FASTACTION, 
                      DO_CHANING_TO_RECIEVE, DO_CHANING_TO_SEND 
FROM         dbo.LETTERITEMSPERMISSION
GO
