USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER TABLE [dbo].[LETTER] ADD [PREVIOUSLETTERID] int NULL
GO
ALTER TABLE [dbo].[LETTER] ADD [NEXTLETTERID] int NULL
GO
ALTER TABLE [dbo].[LETTER] ADD [LASTLETTERID] int NULL
GO
ALTER TABLE [dbo].[LETTER] 
ADD  CONSTRAINT [FK_dbo_LETTER_1]
FOREIGN KEY ([PREVIOUSLETTERID])
REFERENCES [dbo].[LETTER] ( [ID] )
GO
ALTER TABLE [dbo].[LETTER] 
ADD  CONSTRAINT [FK_dbo_LETTER_2]
FOREIGN KEY ([NEXTLETTERID])
REFERENCES [dbo].[LETTER] ( [ID] )
GO
ALTER TABLE [dbo].[LETTER] 
ADD  CONSTRAINT [FK_dbo_LETTER_3]
FOREIGN KEY ([LASTLETTERID])
REFERENCES [dbo].[LETTER] ( [ID] )
GO
