USE [andicator];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER VIEW [dbo].[VIEW_REFERLETTERCOUNT]
AS
SELECT DISTINCT 
LETTERID,LETTERDATE,LETTERSUBJECT, COUNT(LETTERID) AS COUNT
FROM         dbo.REFERLETTER LEFT JOIN LETTER ON LETTER.ID =  REFERLETTER.LETTERID
GROUP BY LETTERID , LETTERDATE,LETTERSUBJECT
GO